In [4]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

# Define the URL for Wikipedia page
url = 'https://en.wikipedia.org/wiki/List_of_largest_Brazilian_companies'

page = requests.get(url)

# Parse the page content
soup = BeautifulSoup(page.text, 'html')

# Find the table containing the list of largest Brazilian companies
soup.find_all('table')[1]

table = soup.find_all('table')[1]

# Extract table headers
world_titles = table.find_all('th')

world_table_titles = [title.text.strip() for title in world_titles]

# Create an empty DataFrame with headers
df = pd.DataFrame(columns = world_table_titles)

column_data = table.find_all('tr')

# Extract each row in the table
for row in column_data[1:]: # Skip the header row
    row_data = row.find_all('td')
    individual_row_data  = [data.text.strip() for data in row_data]

    length = len(df)
    df.loc[length] = individual_row_data

df

,Rank,Forbes 2000 rank,Name,Headquarters,Revenue(billions US$),Profit(billions US$),Assets(billions US$),Value(billions US$),Industry
0,1,54,Petrobras,Rio de Janeiro,99.4,22.3,213.2,92.6,Oil and Gas
1,2,86,Banco Itaú Unibanco,São Paulo,67.8,6.6,525.2,63.7,Banking
2,3,160,Banco do Brasil,Brasília,42.0,3.8,368.4,34.5,Banking
3,4,181,Vale,Rio de Janeiro,41.8,7.8,91.5,55.4,Mining
4,5,223,Banco Bradesco,Osasco,61.2,2.6,390.8,27.9,Banking
5,6,302,BTG Pactual,São Paulo,17.0,2.1,113.4,78.8,Financial services
6,7,652,Nubank,São Paulo,8.1,1.3,43.8,55.6,Financial services
7,8,831,JBS S.A.,São Paulo,74.2,0.4,40.8,12.7,Food production
8,9,850,Eletrobras,Rio de Janeiro,7.4,0.9,52.8,18.6,Utilities
9,10,911,Suzano Papel e Celulose,Salvador,7.7,1.8,28.6,12.9,Pulp and paper
10,11,951,Raízen,São Paulo,44.4,0.8,25.8,6.0,Energy
11,12,956,Itaúsa,São Paulo,1.5,2.7,21.7,20.7,Conglomerate
12,13,1106,WEG Industries,Jaraguá do Sul,6.7,1.2,6.4,32.5,Electrical equipment
13,14,1133,Vibra Energia,Rio de Janeiro,33.1,1.1,8.8,5.0,Oil and Gas
14,15,1145,XP Inc.,São Paulo,3.0,0.8,51.3,11.9,Financial services
15,16,1224,Gerdau Cosiga,São Paulo,13.4,1.3,15.4,8.0,Steel
16,17,1295,Marfrig,São Paulo,27.2,-0.2,26.2,2.1,Food production
17,18,1350,Rede D'Oro Luiz,São Paulo,9.7,0.5,18.2,13.7,Healthcare
18,19,1477,Ultrapar,São Paulo,25.5,0.5,7.4,5.3,Conglomerate
19,20,1520,CPFL Energia,Campinas,8.1,1.1,15.1,7.7,Utilities
20,21,1652,CEMIG,Belo Horizonte,7.4,1.2,11.3,5.8,Utilities
21,22,1658,B3,São Paulo,1.8,0.8,9.8,12.2,Finance
22,23,1727,Braskem,São Paulo,14.0,-1.2,18.7,3.0,Oil and Gas
23,24,1827,Cosan,Rio de Janeiro,7.9,0.2,28.8,5.2,Energy
24,25,1832,Metalurgica Gerdau,Porto Alegre,13.4,0.4,15.4,2.3,Steel
25,26,1915,Sabesp,São Paulo,5.4,0.7,13.3,10.5,Waste management
26,27,1984,Equatorial Energia,São Luís,8.2,0.4,20.1,7.0,Utilities

In [6]:
# Export DataFrame to CSV
df.to_csv('Largest Brazilian Companies According to Wikipedia.csv', index=False)
print("Data exported successfully to csv")

Data exported successfully to csv